# Find NCCL includes and library
#
# NCCL_INCLUDE_DIR - where to find nccl.h
# NCCL_LIBRARY     - nccl.so path
# NCCL_FOUND       - do not attempt to use if "no" or undefined.

FIND_PATH(NCCL_INCLUDE_DIR nccl.h
    HINTS $ENV{NCCL_INCLUDE_PATH} $ENV{NCCL_INCLUDE_DIR} $ENV{NCCL_PREFIX}/include $ENV{NCCL_DIR}/include ${PROJECT_SOURCE_DIR}/include
    PATHS ENV CPP_INCLUDE_PATH
)
FIND_LIBRARY(NCCL_LIBRARY_DIR libnccl.so
    HINTS $ENV{NCCL_LIBRARY_PATH} $ENV{NCCL_LIBRARY_DIR} $ENV{NCCL_PREFIX}/lib $ENV{NCCL_DIR}/lib $ENV{NCCL}/lib ${PROJECT_SOURCE_DIR}/lib
    PATHS ENV LIBRARY_PATH
)

IF(NCCL_INCLUDE_DIR AND NCCL_LIBRARY_DIR)
    SET( NCCL_FOUND "YES" )
    SET( NCCL_DIR $ENV{NCCL_DIR} )
ENDIF()

IF (NCCL_FOUND)
   IF (NOT NCCL_FIND_QUIETLY)
       MESSAGE(STATUS "Found nccl library dir: ${NCCL_LIBRARY_DIR}")
       MESSAGE(STATUS "Found nccl include dir: ${NCCL_INCLUDE_DIR}")
   ENDIF (NOT NCCL_FIND_QUIETLY)
ELSE (NCCL_FOUND)
    IF (NCCL_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find NCCL!")
  ENDIF (NCCL_FIND_REQUIRED)
ENDIF (NCCL_FOUND)
